name: snowflake_cicd -process

#Controls when action will run
on:
  push:
    branches:
      - main
    paths:
      - 'dbcripts/**'
      
  #Allow you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
jobs: 
  snowflake-cicd-showcase:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/setup-python@v3
        with:
          python-version: 3.8.x
          
      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{secrets.SF_ACCOUNT}}
          SF_USERNAME: ${{secrets.SF_USERNAME}}
          SF_ROLE: ${{secrets.SF_ROLE}}
          SF_WAREHOUSE: ${{secrets.SF_WAREHOUSE}}
          SF_DATABASE: ${{secrets.SF_DATABASE}}
          SF_PASSWORD: ${{secrets.SF_PASSWORD}}
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "step 1: Installing schemachange"
          pip install schemachange
          
          
          
          echo "step 2: Running schemachange"
          schemachange -f $GITHUB_WORKSPACE/dbscripts -a $SF_ACCOUNT -u dp -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
    
